language: ruby
rvm:
 - 2.3.1
cache:
 - bundler
before_install:
 - gem update bundler
 - gem update
 - sudo apt-get -qq update
 - sudo apt-get -y install autoconf automake build-essential libass-dev libfreetype6-dev libtheora-dev libtool libvorbis-dev pkg-config texinfo zlib1g-dev libx264-dev libmp3lame-dev
 - sudo apt-get install -y ffmpeg
